# System
gpu_num: 0
seed: 42
debug: False
verbose: False

# Wandb
project_name : "MedicalDataAnalysis2024Main"
run_name: mobilenet_v3_large_sch10_NAdam
wandb_note : "saklas"

# Train / val
val_size: 0.2

# Data Loader
train_data_path : './dataset/train/'
val_data_path : './dataset/val/'
dataset_name : 'AlbumentationsImageFolder'
input_width: 224
input_height: 224
scaler: normalize
transform_name: baseTransform
num_workers: 4
shuffle: True
drop_last: False


# Model

model:
  model_name: mobilenet_v3_large
  args:
    num_classes: 4

# Trainer
n_epochs: 100
batch_size: 16
loss: 
  name: MeanCCELoss # MeanCCELoss
  args:
    weight: [1, 1, 1, 1]
# loss: 
#   name: Focal # MeanCCELoss
#   args:
#     alpha: [0.25,0.25,0.25,0.25]
#     gamma: 2
metrics: 
  - f1-score
  - acc
earlystopping_target: val_f1-score
earlystopping_patience: 5
optimizer:
  name: NAdam
  args:
    lr: 5.0e-04
    weight_decay: 5.0e-02
scheduler:
  name: CosineAnnealingLR
  args:
    T_max: 10
    eta_min: 0

# Logging
plot:
  - loss
  - f1-score
  - acc